# Generated by Django 4.0.3 on 2023-11-09 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('com_num', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SenData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.CharField(max_length=20)),
                ('e', models.CharField(max_length=25)),
                ('ax', models.CharField(max_length=20)),
                ('ay', models.CharField(max_length=20)),
                ('az', models.CharField(max_length=20)),
                ('gx', models.CharField(max_length=20)),
                ('gy', models.CharField(max_length=20)),
                ('gz', models.CharField(max_length=20)),
                ('mx', models.CharField(max_length=20)),
                ('my', models.CharField(max_length=20)),
                ('mz', models.CharField(max_length=20)),
                ('lat', models.CharField(max_length=20)),
                ('lng', models.CharField(max_length=20)),
                ('p', models.CharField(max_length=20)),
                ('s', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SessionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('st', models.CharField(max_length=25)),
                ('et', models.CharField(max_length=20)),
                ('sbt', models.IntegerField()),
                ('wcId', models.CharField(max_length=20)),
                ('sq1', models.CharField(max_length=20)),
                ('sq2', models.CharField(max_length=20)),
                ('sq3', models.CharField(max_length=20)),
                ('eq1', models.CharField(max_length=20)),
                ('eq2', models.CharField(max_length=20)),
                ('v', models.CharField(default='old', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Wheelchair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_wc', models.CharField(blank=True, max_length=20)),
                ('wc_identify', models.CharField(max_length=20)),
                ('number_w', models.IntegerField(blank=True, null=True)),
                ('d_type', models.CharField(blank=True, max_length=20)),
                ('tire_mat', models.CharField(blank=True, max_length=20)),
                ('wc_wdt', models.IntegerField(blank=True, null=True)),
                ('wc_ht', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(blank=True, max_length=20)),
                ('weight', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('age', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
