# Generated by Django 4.0.3 on 2023-02-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=200)),
                ('tc', models.BooleanField()),
                ('height', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('type_wc', models.CharField(max_length=20)),
                ('number_w', models.CharField(max_length=20)),
                ('wheel_type', models.CharField(max_length=20)),
                ('tire_mat', models.CharField(max_length=20)),
                ('wc_wdt', models.CharField(max_length=20)),
                ('wc_ht', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SenData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.CharField(max_length=20)),
                ('e', models.CharField(max_length=25)),
                ('ax', models.CharField(max_length=20)),
                ('ay', models.CharField(max_length=20)),
                ('az', models.CharField(max_length=20)),
                ('gx', models.CharField(max_length=20)),
                ('gy', models.CharField(max_length=20)),
                ('gz', models.CharField(max_length=20)),
                ('mx', models.CharField(max_length=20)),
                ('my', models.CharField(max_length=20)),
                ('mz', models.CharField(max_length=20)),
                ('lat', models.CharField(max_length=20)),
                ('lng', models.CharField(max_length=20)),
                ('p', models.CharField(max_length=20)),
                ('s', models.CharField(max_length=20)),
            ],
        ),
    ]
