# Generated by Django 4.0.3 on 2023-08-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_sessiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiondata',
            name='pp',
            field=models.CharField(default='-1', max_length=25),
        ),
        migrations.AddField(
            model_name='sessiondata',
            name='v',
            field=models.CharField(default='old', max_length=25),
        ),
    ]
