# Generated by Django 4.0.3 on 2024-05-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tc',
            field=models.BooleanField(default=True),
        ),
    ]
